"""Malmus baseline — structured LLM feature engineering with JSON mode.

Uses structured JSON output (via DeepSeek native or LiteLLM) to generate
feature definitions with name, code, description, and library dependencies.
This replaces free-text code generation with reliable structured parsing.

Supports two modes:
- single_shot (default): One LLM call generates all features at once.
- iterative: Sequential LLM calls, one feature at a time, with CV-based
  keep/discard decisions after each iteration.
"""

from __future__ import annotations

import json
from typing import Any, Literal

import pandas as pd
from pydantic import BaseModel, Field, ValidationError

from feature_forge.artifacts.base import ArtifactConfig
from feature_forge.config import Settings, get_settings
from feature_forge.evaluation.cv import CVEvaluator
from feature_forge.evaluation.sandbox import SandboxedExecutor
from feature_forge.exceptions import EvaluationError
from feature_forge.llm.base import LLMClient
from feature_forge.llm.factory import create_llm_client
from feature_forge.methods.base import BaseMethod
from feature_forge.methods.malmus.prompts import (
    MalmusIterativeParams,
    MalmusSingleShotParams,
    get_registry,
)
from feature_forge.observability.structlog_config import get_logger
from feature_forge.utils import run_coro_sync

logger = get_logger(__name__)


def _ensure_json_object(raw: object) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise EvaluationError(f"Expected JSON object, got {type(raw).__name__}")
    return raw


class FeatureDefinition(BaseModel):
    """A single feature generated by the LLM."""

    name: str = Field(description="Valid Python identifier for the feature column")
    code: str = Field(description="Python expression or function body producing the feature")
    description: str = Field(description="Human-readable explanation of what this feature does")
    libraries: list[str] = Field(
        default_factory=list,
        description="Required libraries (e.g. ['pandas', 'numpy'])",
    )


class StructuredFeatureOutput(BaseModel):
    """Structured JSON schema for LLM feature generation responses."""

    features: list[FeatureDefinition] = Field(description="List of generated feature definitions")


FEATURE_SCHEMA_DESCRIPTION = json.dumps(
    StructuredFeatureOutput.model_json_schema(),
    indent=2,
)

ITERATIVE_FEATURE_SCHEMA_DESCRIPTION = json.dumps(
    {
        "type": "object",
        "properties": {
            "features": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string", "description": "Python identifier"},
                        "code": {
                            "type": "string",
                            "description": "Python expression producing the feature from df",
                        },
                        "description": {"type": "string"},
                        "libraries": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                    "required": ["name", "code", "description"],
                },
            }
        },
        "required": ["features"],
    },
    indent=2,
)


class MalmusMethod(BaseMethod):
    """Structured LLM feature engineering baseline with JSON mode.

    Uses DeepSeek as the default provider with native JSON mode optimizations,
    and LiteLLM as the unified interface for all other providers.

    Unlike free-text baselines (LLMFE, CAAFE), Malmus forces the LLM to
    return structured JSON with per-feature metadata, enabling:
    - Reliable parsing without regex/markdown-fence stripping
    - Per-feature provenance tracking (name, description, libraries)
    - Safer execution with explicit library dependency declarations

    Parameters:
        llm_client: LLM client supporting `complete_json()`. Defaults to
            DeepSeekProvider.
        n_features: Number of features to generate (single_shot) or
            iterations (iterative).
        mode: 'single_shot' or 'iterative'.
        evaluator: CVEvaluator for iterative mode.
        artifact_config: Configuration for artifact storage.
    """

    def __init__(
        self,
        llm_client: LLMClient | None = None,
        settings: Settings | None = None,
        n_features: int = 5,
        mode: Literal["single_shot", "iterative"] = "single_shot",
        evaluator: CVEvaluator | None = None,
        artifact_config: ArtifactConfig | None = None,
    ) -> None:
        super().__init__("malmus", artifact_config=artifact_config)
        if llm_client is not None:
            self.llm_client = llm_client
        else:
            s = settings or get_settings()
            self.llm_client = create_llm_client(s.llm, s.retry)
        self.n_features = n_features
        self.mode = mode
        self.evaluator = evaluator
        self.sandbox = SandboxedExecutor.from_evaluator(evaluator)
        self._feature_defs: list[FeatureDefinition] = []

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> MalmusMethod:
        run_coro_sync(self.async_fit(X_train, y_train))
        return self

    async def async_fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> None:
        if self.mode == "iterative":
            await self._fit_iterative(X_train, y_train)
        else:
            await self._fit_single_shot(X_train, y_train)

    async def _fit_single_shot(self, X: pd.DataFrame, y: pd.Series) -> None:
        template = get_registry().get("single_shot").system
        params = MalmusSingleShotParams(
            columns=", ".join(X.columns),
            task="classification" if y.nunique() <= 10 else "regression",
            n_features=self.n_features,
        )
        prompt = params.render(template)
        raw_json = await self.llm_client.complete_json(
            messages=[{"role": "user", "content": prompt}],
            schema_description=FEATURE_SCHEMA_DESCRIPTION,
            temperature=0.3,
            max_tokens=4096,
        )
        self._artifacts["raw_json"] = raw_json
        self._artifacts["prompt"] = prompt

        parsed = self._parse_response(_ensure_json_object(raw_json))
        self._feature_defs = parsed.features
        self._artifacts["generated_code"] = self._defs_to_code(parsed.features)
        self._artifacts["feature_definitions"] = [f.model_dump() for f in parsed.features]

    async def _fit_iterative(self, X: pd.DataFrame, y: pd.Series) -> None:
        evaluator = self.evaluator or CVEvaluator()
        baseline_score = evaluator.evaluate_baseline(X, y)
        self._artifacts["baseline_score"] = baseline_score

        iterations: list[dict[str, Any]] = []
        cumulative_cols: list[str] = []
        all_defs: list[FeatureDefinition] = []
        feedback_str = ""
        task: Literal["classification", "regression"] = (
            "classification" if y.nunique() <= 10 else "regression"
        )
        cols = ", ".join(X.columns)

        for i in range(self.n_features):
            template = get_registry().get("iterative").system
            params = MalmusIterativeParams(
                columns=cols,
                task=task,
                n_iterations=self.n_features,
                iteration=i + 1,
                existing_features=", ".join(cumulative_cols) if cumulative_cols else "none",
                feedback=feedback_str,
            )
            prompt = params.render(template)
            raw_json = await self.llm_client.complete_json(
                messages=[{"role": "user", "content": prompt}],
                schema_description=ITERATIVE_FEATURE_SCHEMA_DESCRIPTION,
                temperature=0.3,
                max_tokens=4096,
            )

            iteration_record: dict[str, Any] = {
                "iteration": i,
                "prompt": prompt,
                "raw_json": raw_json,
            }

            try:
                parsed = self._parse_response(_ensure_json_object(raw_json))
                code_block = self._defs_to_code(parsed.features)
                iteration_record["feature_definitions"] = [f.model_dump() for f in parsed.features]
                iteration_record["generated_code"] = code_block

                new_features = self.sandbox.execute(code_block, X)
                kept_features = pd.DataFrame(index=X.index)
                kept_gains: dict[str, float] = {}

                for col in new_features.columns:
                    gain = evaluator.evaluate_feature(
                        X,
                        y,
                        new_features[[col]],
                        baseline_score=baseline_score,
                    )
                    if gain > 0:
                        kept_features[col] = new_features[col].values
                        kept_gains[col] = gain
                        cumulative_cols.append(col)
                        matching_def = next(
                            (d for d in parsed.features if d.name == col),
                            None,
                        )
                        if matching_def:
                            all_defs.append(matching_def)

                iteration_record["all_new_features"] = self._storage.store(
                    f"malmus_iter_{i}_all",
                    new_features,
                )
                iteration_record["kept_features"] = self._storage.store(
                    f"malmus_iter_{i}_kept",
                    kept_features,
                )
                iteration_record["gains"] = kept_gains
                iteration_record["kept"] = len(kept_gains) > 0

                if kept_gains:
                    feedback_parts = [
                        f"{col}: gain={g:.4f} ({'kept' if g > 0 else 'discarded'})"
                        for col, g in kept_gains.items()
                    ]
                    feedback_str = "Previous iteration feedback: " + "; ".join(feedback_parts)

            except Exception as exc:
                iteration_record["error"] = str(exc)
                iteration_record["kept"] = False
                feedback_str = f"Previous iteration failed: {exc}"
                logger.warning("malmus_iteration_failed", iteration=i, error=str(exc))

            iterations.append(iteration_record)

        self._feature_defs = all_defs
        self._artifacts["iterations"] = iterations
        self._artifacts["feature_definitions"] = [d.model_dump() for d in all_defs]
        self._artifacts["generated_code"] = "\n\n".join(
            it.get("generated_code", "") for it in iterations if it.get("generated_code")
        )

    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        if not self._feature_defs:
            raise RuntimeError("MalmusMethod not fitted yet")
        code = self._defs_to_code(self._feature_defs)
        try:
            return self.sandbox.execute(code, X)
        except Exception as exc:
            raise EvaluationError(f"Malmus transform failed: {exc}") from exc

    @property
    def generated_scripts(self) -> list[str]:
        if self.mode == "iterative":
            iterations = self._artifacts.get("iterations", [])
            return [it.get("generated_code", "") for it in iterations if it.get("generated_code")]
        code = self._artifacts.get("generated_code", "")
        return [code] if code else []

    @property
    def feature_metadata(self) -> list[dict[str, Any]]:
        iterations = self._artifacts.get("iterations")
        if iterations:
            meta: list[dict[str, Any]] = []
            for it in iterations:
                for col, gain in it.get("gains", {}).items():
                    defs = it.get("feature_definitions", [])
                    matching: dict[str, Any] = next((d for d in defs if d.get("name") == col), {})
                    meta.append(
                        {
                            "name": col,
                            "method": "malmus",
                            "iteration": it.get("iteration"),
                            "gain": gain,
                            "kept": it.get("kept", False),
                            "description": matching.get("description", ""),
                            "libraries": matching.get("libraries", []),
                        }
                    )
            return meta

        defs = self._artifacts.get("feature_definitions", [])
        return [
            {
                "name": d.get("name", ""),
                "method": "malmus",
                "description": d.get("description", ""),
                "libraries": d.get("libraries", []),
                "code": d.get("code", ""),
            }
            for d in defs
        ]

    @property
    def provenance_records(self) -> list[dict[str, Any]]:
        base = self._iterative_provenance_records("malmus")
        if not base:
            return []
        iterations = self._artifacts.get("iterations", [])
        for record, iteration in zip(
            base,
            [it for it in iterations for _ in it.get("gains", {})],
            strict=True,
        ):
            defs = iteration.get("feature_definitions", [])
            matching: dict[str, Any] = next(
                (d for d in defs if d.get("name") == record["feature_name"]), {}
            )
            record["description"] = matching.get("description", "")
            record["libraries"] = matching.get("libraries", [])
        return base

    @staticmethod
    def _parse_response(raw_json: dict[str, Any]) -> StructuredFeatureOutput:
        try:
            return StructuredFeatureOutput.model_validate(raw_json)
        except ValidationError as exc:
            raise EvaluationError(f"LLM returned invalid structured output: {exc}") from exc

    @staticmethod
    def _defs_to_code(features: list[FeatureDefinition]) -> str:
        """Convert feature definitions to an executable code block.

        Generates a `generate_features(df)` function that computes
        each feature using its code expression.
        """
        if not features:
            return "def generate_features(df):\n    return pd.DataFrame(index=df.index)"
        lines = ["import pandas as pd", "import numpy as np", "", "", "def generate_features(df):"]
        lines.append("    result = pd.DataFrame(index=df.index)")
        for feat in features:
            lines.append(f"    # {feat.description}")
            lines.append(f"    result['{feat.name}'] = {feat.code}")
        lines.append("    return result")
        return "\n".join(lines)
