"""Versioned contracts for durable experiment artifacts and runs."""

from feature_forge.contracts.artifacts import (
    ArtifactDescriptor,
    ArtifactNamespace,
    ArtifactRef,
    ManifestRef,
    RelativePath,
    RunId,
    Sha256,
)
from feature_forge.contracts.base import EvaluationProtocol
from feature_forge.contracts.datasets import (
    BronzeMaterialization,
    BronzeRecord,
    DatasetComputationRequest,
    DatasetRequest,
    SilverMaterialization,
    SilverPackage,
)
from feature_forge.contracts.gold import (
    FeatureCandidate,
    FeatureDecision,
    FeatureDecisionState,
    FeatureProvenance,
    GoldFeatureCounts,
    GoldMaterialization,
    GoldPackage,
    GoldRequest,
)
from feature_forge.contracts.identity import (
    IDENTITY_SCHEMA_VERSION,
    PLATINUM_IDENTITY_SCHEMA_VERSION,
    MethodIdentity,
    bronze_fingerprint,
    gold_input_fingerprint,
    gold_materialization_fingerprint,
    platinum_input_fingerprint,
    silver_fingerprint,
)
from feature_forge.contracts.materialization import Materialization
from feature_forge.contracts.orchestration import (
    CaseExecutionPlan,
    ResumePlan,
    ResumePolicy,
    ResumeStageDecision,
    StageDisposition,
    StageExecution,
)
from feature_forge.contracts.platinum import (
    AggregateMetric,
    EvaluationPolicy,
    ModelSpecification,
    PlatinumEvidenceIndex,
    PlatinumMaterialization,
    PlatinumPackage,
    PlatinumRequest,
    PlatinumSelectionDecision,
    SelectionPolicy,
    UncertaintyPolicy,
    UncertaintySummary,
)
from feature_forge.contracts.runs import (
    EnvironmentSnapshot,
    RunManifest,
    RunRequest,
)
from feature_forge.contracts.stages import (
    CheckResult,
    CheckSeverity,
    FailureClass,
    Layer,
    RunState,
    StageResult,
    VerificationReport,
)

__all__ = [
    "IDENTITY_SCHEMA_VERSION",
    "PLATINUM_IDENTITY_SCHEMA_VERSION",
    "AggregateMetric",
    "ArtifactDescriptor",
    "ArtifactNamespace",
    "ArtifactRef",
    "BronzeMaterialization",
    "BronzeRecord",
    "CaseExecutionPlan",
    "CheckResult",
    "CheckSeverity",
    "DatasetComputationRequest",
    "DatasetRequest",
    "EnvironmentSnapshot",
    "EvaluationPolicy",
    "EvaluationProtocol",
    "FailureClass",
    "FeatureCandidate",
    "FeatureDecision",
    "FeatureDecisionState",
    "FeatureProvenance",
    "GoldFeatureCounts",
    "GoldMaterialization",
    "GoldPackage",
    "GoldRequest",
    "Layer",
    "ManifestRef",
    "Materialization",
    "MethodIdentity",
    "ModelSpecification",
    "PlatinumEvidenceIndex",
    "PlatinumMaterialization",
    "PlatinumPackage",
    "PlatinumRequest",
    "PlatinumSelectionDecision",
    "RelativePath",
    "ResumePlan",
    "ResumePolicy",
    "ResumeStageDecision",
    "RunId",
    "RunManifest",
    "RunRequest",
    "RunState",
    "SelectionPolicy",
    "Sha256",
    "SilverMaterialization",
    "SilverPackage",
    "StageDisposition",
    "StageExecution",
    "StageResult",
    "UncertaintyPolicy",
    "UncertaintySummary",
    "VerificationReport",
    "bronze_fingerprint",
    "gold_input_fingerprint",
    "gold_materialization_fingerprint",
    "platinum_input_fingerprint",
    "silver_fingerprint",
]
