"""Shared type aliases and models for feature_forge."""

from __future__ import annotations

from pydantic import BaseModel, Field


class FeatureSpec(BaseModel):
    """Feature specification generated by an agent."""

    name: str
    type: str = "numerical"
    transform: str = ""
    logic: str = ""
    base_columns: list[str] = Field(default_factory=list)
    agent_name: str = ""
