"""Router & Pipeline Modes — dynamic agent selection with data-driven, performance-driven, hybrid, and LLM strategies."""

import os
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

warnings.filterwarnings("ignore")
os.environ.setdefault("FF_LOG_LEVEL", "warning")

print("Router & Pipeline Modes Demo")


def main():
    X, y = make_classification(
        n_samples=250, n_features=8, n_informative=5, random_state=42
    )
    df = pd.DataFrame(X, columns=[f"col_{i+1}" for i in range(X.shape[1])])
    df["target"] = y

    from feature_forge.agents.router import RouterAgent
    from feature_forge.config import LLMConfig, RouterConfig, Settings

    settings = Settings(
        task="classification",
        router=RouterConfig(strategy="hybrid"),
        llm=LLMConfig(
            model="deepseek-chat",
            api_key=os.environ.get("FF_LLM__API_KEY", ""),
        ),
    )

    router = RouterAgent(settings)

    description = {c: {"type": "numerical"} for c in df.columns if c != "target"}
    characteristics = router.analyze_dataset(
        df.drop(columns=["target"]), description=description
    )
    print("Dataset characteristics:")
    for k, v in characteristics.items():
        print(f"  {k}: {v}")

    router_dd = RouterAgent(Settings(router=RouterConfig(strategy="data_driven")))
    router_dd.dataset_characteristics = characteristics
    selected_dd = router_dd._data_driven_selection()
    print(f"\nData-driven selected: {selected_dd}")

    router_perf = RouterAgent(Settings(router=RouterConfig(strategy="performance_driven")))
    for agent in router_perf.agent_names:
        router_perf.agent_performance[agent] = [np.random.uniform(0.01, 0.05) for _ in range(3)]

    selected_perf = router_perf._performance_driven_selection()
    print(f"Performance-driven selected: {selected_perf}")

    router_llm = RouterAgent(
        Settings(router=RouterConfig(strategy="llm")),
        llm_client=None,
    )
    print(f"\nLLM router strategy: {router_llm.strategy}")
    print(f"LLM router prompt length: {len(router_llm.router_prompt)} chars")

    from feature_forge.api import MALMASFeatureEngineer

    config = Settings(
        task="classification",
        n_rounds=1,
        llm=LLMConfig(
            model="deepseek-chat",
            api_key=os.environ.get("FF_LLM__API_KEY", ""),
        ),
    )

    X_data = df.drop(columns=["target"])
    y_data = df["target"]

    ablations = {
        "full": "full",
        "no_memory": "no_memory",
        "no_router": "no_router",
        "unary_only": "unary",
    }

    ablation_results = {}
    for name, mode in ablations.items():
        try:
            fe = MALMASFeatureEngineer(config=config, mode=mode)
            fe.fit(X_data, y_data)
            ablation_results[name] = {
                "features": len(fe.selected_features),
                "codes": len(fe.feature_codes),
                "transform_failures": len(fe.transform_failures),
            }
        except Exception as exc:
            ablation_results[name] = {"error": str(exc)[:120]}

    abl_df = pd.DataFrame.from_dict(ablation_results, orient="index")
    print("\nAblation results:")
    print(abl_df)

    abl_df_plot = pd.DataFrame.from_dict(ablation_results, orient="index")
    if "features" in abl_df_plot.columns:
        abl_df_plot = abl_df_plot.dropna(subset=["features"])
        fig, ax = plt.subplots(figsize=(8, 4))
        abl_df_plot["features"].plot(kind="barh", ax=ax, color="coral")
        ax.set_title("Features Generated by Pipeline Mode")
        ax.set_xlabel("Feature Count")
        plt.tight_layout()
        plt.savefig("/tmp/03_router_ablation.png", dpi=100)
        plt.close()
        print("Plot saved to /tmp/03_router_ablation.png")


if __name__ == "__main__":
    main()
